# varsionを指定 circleciの現在は2
version: 2

# 各ジョブの設定を実行
jobs:
  # ビルドのジョブを指定
  build:
    # ビルドで利用するイメージを設定
    docker:
      - image: node:8
    steps:
      # sourceのチェックアウト
      - checkout
      # 走らせるスクリプトを設定
      - run:
          name: Update npm
          command: 'yarn install'
      - save_cache:
          key: dependency-cache
          paths:
            - node_modules
  test:
    requires:
      - build
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
          paths:
            - node_modules
      - run:
          name: Test
          command: 'yarn test a --no-watch'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
